import type { Metadata } from 'next';
import { LegalPage, type LegalSection } from '@/components/creator/LegalPage';

export const metadata: Metadata = { title: 'Terms & Conditions | Alina Popova Studio' };

const sections: LegalSection[] = [
  { title: 'About the studio', paragraphs: ['Alina Popova Studio is a creator-led marketing agency. We provide marketing services to companies and maintain a selection-based creator network for independent adult creators.'] },
  { title: 'Acceptance and eligibility', paragraphs: ['By using this website, submitting an inquiry, submitting a creator application, or communicating with the studio, you agree to these Terms, the Privacy Policy, Safety Policy, and relevant campaign or creator summaries. Creator applications are only accepted from people aged 18 or older.'] },
  { title: 'Creator applications and relationship', paragraphs: ['Applying is free. There is no joining fee or training debt. An application, roster placement, or optional training does not guarantee selection, work, income, or a fixed number of opportunities.', 'Creators are generally independent creator partners unless a separate employment agreement says otherwise. They may accept or decline opportunities, work elsewhere unless a separate exclusivity agreement exists, and refuse any outfit, script, location, format, or use they do not accept.'] },
  { title: 'Company services and campaign scope', paragraphs: ['A company inquiry is not a confirmed booking. Campaign pricing, deliverables, timelines, revisions, approvals, creator availability, usage rights, and payment terms are confirmed only through a written proposal, invoice, acceptance, or agreement.', 'Only written scope is included. Extra revisions, reshoots, creator time, paid usage, whitelisting, exclusivity, or out-of-scope requests may require a revised scope and fee.'] },
  { title: 'Content usage and intellectual property', paragraphs: ['Companies may use creator content only within the written rights agreed for the campaign. Paid media, whitelisting, edits, repurposing, perpetual rights, exclusivity, geographic rights, and third-party distribution require express written permission.', 'Website assets belong to Alina Popova Studio or its licensors. Ownership of campaign assets depends on the written campaign terms.'] },
  { title: 'Payments, refunds, and no guarantees', paragraphs: ['Company payments follow the relevant proposal or invoice. Creator payouts and any disclosed creator-side fee or commission follow written campaign confirmation. Hidden creator deductions are not supported.', 'We do not guarantee creator selection, creator income, company sales, virality, follower growth, brand deals, or platform results. Refunds, cancellations, rescheduling, and revisions are governed by the Refund Policy and the applicable written scope.'] },
  { title: 'Safety, conduct, and termination', paragraphs: ['We do not support adult, obscene, illegal, exploitative, coercive, harassing, hidden-camera, unsafe, or unpaid commercial creator work. Unsafe conduct may lead to rejection, campaign pause, removal, termination, or escalation where required.', 'The studio may refuse an application, pause or decline work, or end access where safety, law, professional conduct, or written obligations require it.'] },
  { title: 'Privacy, liability, and disputes', paragraphs: ['Personal data is handled under the Privacy Policy. We are not responsible for indirect loss, lost profit, platform algorithm changes, third-party outages, company product issues, or events outside reasonable control.', 'These Terms are governed by the laws of India, subject to applicable law. We encourage good-faith resolution first. Policies may be updated, with the current version date displayed on the relevant page.'] }
];

const meaning = {
  companies: ['An inquiry is not a confirmed booking or promise of sales, virality, or platform results.', 'Campaign scope, creator acceptance, usage rights, pricing, and timing must be confirmed in writing.'],
  creators: ['Applying is free and does not guarantee selection, paid work, or income.', 'You can accept or decline opportunities and refuse any work, use, or location you do not accept.']
};

export default function TermsPage() { return <LegalPage eyebrow="Terms" title="Terms & Conditions" description="The rules for using Alina Popova Studio, submitting company briefs, applying as a creator, and working through written campaign terms." summary="Alina Popova Studio is a creator-led marketing agency. A company inquiry is not a confirmed campaign, and a creator application does not guarantee selection, work, or income. Campaign scope, pricing, usage rights, timelines, deliverables, and payouts are confirmed only through written proposal, acceptance, or agreement." sections={sections} meaning={meaning} />; }
